from playwright.sync_api import sync_playwright
errs=[]
with sync_playwright() as p:
    b=p.chromium.launch(args=['--use-gl=swiftshader','--enable-unsafe-swiftshader'])
    pg=b.new_page(viewport={'width':1600,'height':1000})
    pg.on('pageerror', lambda e: errs.append(str(e)[:250]))
    pg.goto('file:///home/claude/canvas_v10.html'); pg.wait_for_timeout(1800)
    def js(e):
        try: return pg.evaluate(e)
        except Exception as ex: return "THREW "+str(ex)[:200]
    def vis(): return js("Array.from(document.querySelectorAll('#acad-tabs .acad-tab')).filter(e=>e.style.display!=='none').map(e=>e.textContent).join(' | ')")
    def label(): return js("(document.querySelector('.acad-ws')||{}).textContent.trim()")
    print("default label:", label())
    print("default tabs :", vis())
    print()
    js("document.querySelector('.acad-ws').click()"); pg.wait_for_timeout(400)
    print("dropdown entries:", js("Array.from(document.querySelectorAll('#acad-wsmenu .wsm-item')).map(e=>e.textContent.trim()).join(' | ')"))
    print()
    js("(()=>{var i=document.querySelector('[data-wsm=\"canvas\"]');if(i)i.click();})()"); pg.wait_for_timeout(600)
    print("CANVAS label:", label())
    print("CANVAS tabs :", vis())
    print("  active tab:", js("(document.querySelector('#acad-tabs .acad-tab.active')||{}).textContent"))
    print("  Insert has whiteboard tools:", js("""(()=>{var t=Array.from(document.querySelectorAll('#acad-panels')).map(e=>e.textContent).join('');
      return ['Card','Sticky','Board','Table','Chart','Image'].filter(w=>t.indexOf(w)>=0).join(',');})()"""))
    print()
    js("document.querySelector('.acad-ws').click()"); pg.wait_for_timeout(300)
    js("(()=>{var i=document.querySelector('[data-wsm=\"da\"]');if(i)i.click();})()"); pg.wait_for_timeout(600)
    print("D&A label:", label())
    print("D&A tabs :", vis())
    print("  Home has CAD tools:", js("""(()=>{var t=document.querySelector('#acad-panels').textContent;
      return ['Line','Polyline','Trim','Fillet','Offset','Hatch'].filter(w=>t.indexOf(w)>=0).join(',');})()"""))
    print()
    js("document.querySelector('.acad-ws').click()"); pg.wait_for_timeout(300)
    js("(()=>{var i=document.querySelector('[data-wsm=\"3d\"]');if(i)i.click();})()"); pg.wait_for_timeout(1200)
    print("3D label:", label())
    print("3D tabs :", vis())
    print("  active tab:", js("(document.querySelector('#acad-tabs .acad-tab.active')||{}).textContent"))
    print("  3D workspace live:", js("!!window.__a3dOn"))
    print()
    js("document.querySelector('.acad-ws').click()"); pg.wait_for_timeout(300)
    js("(()=>{var i=document.querySelector('[data-wsm=\"canvas\"]');if(i)i.click();})()"); pg.wait_for_timeout(900)
    print("3D -> Canvas label:", label())
    print("3D -> Canvas tabs :", vis())
    print("  3D exited cleanly:", js("!window.__a3dOn"))
    print("  3D Tools tab hidden:", js("""(()=>{var b=document.querySelector('[data-acad-tab=\"a3dtools\"]');
      return b? (b.style.display==='none') : 'tab removed';})()"""))
    print()
    print("errors:", errs if errs else "none")
    pg.screenshot(path='/home/claude/ws_canvas.png')
    b.close()
